USE [master]
GO

/****** Object:  Database [AW_Marketing]    Script Date: 10/23/2017 10:02:50 AM ******/
CREATE DATABASE [AW_Marketing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AW_Marketing_Data1', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AW_Marketing_Data1.mdf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [ArchivedData] 
( NAME = N'AW_Marketing_Data3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AW_Marketing_Data3.ndf' , SIZE = 25600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [CurrentData] 
( NAME = N'AW_Marketing_Data2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AW_Marketing_Data2.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'AW_Marketing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AW_Marketing_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 0)
GO

ALTER DATABASE [AW_Marketing] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AW_Marketing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AW_Marketing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AW_Marketing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AW_Marketing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AW_Marketing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AW_Marketing] SET ARITHABORT OFF 
GO

ALTER DATABASE [AW_Marketing] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AW_Marketing] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [AW_Marketing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AW_Marketing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AW_Marketing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AW_Marketing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AW_Marketing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AW_Marketing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AW_Marketing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AW_Marketing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AW_Marketing] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AW_Marketing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AW_Marketing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AW_Marketing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AW_Marketing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AW_Marketing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AW_Marketing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AW_Marketing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AW_Marketing] SET RECOVERY FULL 
GO

ALTER DATABASE [AW_Marketing] SET  MULTI_USER 
GO

ALTER DATABASE [AW_Marketing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AW_Marketing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AW_Marketing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AW_Marketing] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [AW_Marketing] SET  READ_WRITE 
GO

